### ISSUE TITLE
BRAT does not recognise and install the update(s)

### ISSUE THREAD

**Issue by stef-rausch** [HananoshikaYomaru/obsidian-run#10]
**Describe the bug**

I am still on version `1.0.1` and am trying to update to `1.0.3` via `BRAT` -- does not recognise the latest update(s).

**To Reproduce**

Run the `BRAT: Plugins: Check for updates for all beta plugins and UPDATE` or `BRAT: Plugins: Choose a single version to update` command.

See the info message: `BRAT No update available for HananoshikaYomaru/obsidian-run`, when running the single version update command.

**Expected behavior**

`Brat` to install the latest update.

**Additional context**

```
SYSTEM INFO:

Obsidian version: v1.4.14
Installer version: v1.4.14
Operating system: Windows 11 Home Single Language 10.0.22621
Login status: logged in
Catalyst license: supporter
Insider build toggle: on
Live preview: on
Legacy editor: off
Base theme: light
Community theme: Minimal v7.2.3
Snippets enabled: 33
Restricted mode: off
Plugins installed: 49
Plugins enabled: 43
```

**Comment by HananoshikaYomaru** [comment]
HananoshikaYomary/obsidian-run

There is a typo. I am not sure if this cause the problem

**Comment by stef-rausch** [comment]
Thanks for the hint; I misspelt it -- `BRAT` does use the first install `GitHub` URL, and I have not to type it out.

*I have corrected the original post*.

The issue persists.

**Comment by HananoshikaYomaru** [comment]
interesting, I haven't heard of BRAT before. Thx for telling. Seems like a pretty good channel to publish your plugin before obsidian team's official approval.

**Comment by stef-rausch** [comment]
It is a fantastic tool for, amongst others, automatically updating beta versions of plugins for testing purposes.

It has a ton of additional functionality most people don't realise: it is a gem!

**Comment by HananoshikaYomaru** [comment]
![CleanShot 2023-10-04 at 09 45 54@2x](https://github.com/HananoshikaYomaru/obsidian-run/assets/43137033/d98859cd-b668-4b6b-b76a-85ad98fb5dc0)

now it should work. it didn't work because I forget to run `bun version` to update the manifest version number

**Comment by stef-rausch** [comment]
Yeah! Thank you for sorting this out. 👏
