### ISSUE TITLE
inline run block

### ISSUE THREAD

**Issue by HananoshikaYomaru** [HananoshikaYomaru/obsidian-run#11]
**Is your feature request related to a problem? Please describe.**

```md
this is my %%= 3%% note
```

**Describe the solution you'd like**
1. inline expression only work on simple javascript expression but not multiple statements
2. if user really multiple lines statement, they can use the user defined script with templater

**Comment by HananoshikaYomaru** [comment]
I don't want the syntax to be clumsy so using ending tag might not be a good idea. But need to think about this first.

**Comment by stef-rausch** [comment]
Why not stay traditional and, e.g., use the inline code block with an additional identifier, like `Dataview` does?

What about `r= 3` -- `r` for `Run`. 😉

**Comment by HananoshikaYomaru** [comment]
it is difficult because dataview doesn't generate markdown at all, all it does it just render the result in the viewing mode. For run to know the previous content so that it can replace it, it must have an ending tag or some other way to keep track of the previous result.

**Comment by stef-rausch** [comment]
Okay... what about `p= <expression> =q`? If the user needs to use `backticks` in the expression, they can be escaped.

I think it would be a visual enhancement to see the inline run block rendered as an inline code block.

**Comment by HananoshikaYomaru** [comment]
Then the p= =q will be visible as markdown.

**Comment by HananoshikaYomaru** [comment]
I rarely encounter use cases that I need to use inline run block.
