### ISSUE TITLE
Does not support comments in codeblock

### ISSUE THREAD

**Issue by NitishPuri** [HananoshikaYomaru/obsidian-run#22]
**Describe the bug**
Adding a comment to codeblock results in the error shown below in screenshot.

**Expected behavior**
A comment should have no additional effect as expected

**Screenshots**
![image](https://github.com/HananoshikaYomaru/obsidian-run/assets/4450226/7233e415-75e9-4078-b0b5-688fc93084e0)

**Comment by HananoshikaYomaru** [comment]
Nice catch. Thank you for reporting.
