### ISSUE TITLE
Help needed: I dont understand how to run this plugin

### ISSUE THREAD

**Issue by natarslan** [HananoshikaYomaru/obsidian-run#23]
My steps:

- Download obsidian run plugin
- Download obsidian custom save plugin
- Add "run: run file" command to custom save plugin
- Created a new md file in vault
- Added a dataview code like following

`
%% run start
```ts
dv.list from "" where file.cday = date("<%tp.date.now(\"YYYY-MM-DD\")%>") sort file.ctime asc
```
%%
`

At this point I have no idea what to do next to get a markdown/text from the dataview query. Can someone please help me?

**Comment by HananoshikaYomaru** [comment]
You have to run JavaScript. The code that you write is not JavaScript at all. Also you can have a look at https://github.com/HananoshikaYomaru/obsidian-run/issues/21

**Comment by natarslan** [comment]
Thanks for the answer. I tried finding some examples with dataview and wasnt sure how to write a js for it. I'll look into it.
