### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by rodrigoportela** [HananoshikaYomaru/obsidian-run#24]
I'm not sure if this is a bug coming from Run or there's another cause.

Trying to use Run on Android devices, seeing no previous warning that there would be a problem with the device, I click the Enable button and always receive the "Failed to load plugin run" error. I have all the files in the vault in sync among devices, including the settings, and the plugin is working on the computer.

Is the plugin not expected to work on Android or is there any known problem which would be causing this?

**Comment by HananoshikaYomaru** [comment]
Maybe it doesn't work on mobile. It is not tested on mobile and windows.

**Comment by Teloshav** [comment]
Aww man! Is there any reconsideration that you'd have it run on Android/mobile devices?

I'll see what I can do but it is truly a shame that it doesn't work currently.

Unrelated but I am going to donate some money to say thanks for this extension, it's been AMAZING to use. Having proper code running on my notes in a format that actually MODIFIES the text on the note itself is HUGE for me. :D

Thanks for the work!

 - Teloshav
