### ISSUE TITLE
remove id from the syntax

### ISSUE THREAD

**Issue by HananoshikaYomaru** [HananoshikaYomaru/obsidian-run#3]
the `id` is confusing. let's remove this. 
- [ ] update the doc as well.

**Comment by stef-rausch** [comment]
I agree. The `id` is not of any use for the user.

Or do you have any future plans how to leverage the `id`?

**Comment by HananoshikaYomaru** [comment]
the `id` only serve 1 purpose, make it easier to target Run block. For example, if there are two identical run blocks, the program might have replace the content in the first run block 2 times. `id` make it unique so the program won't target wrong. 

In other words, the id is just a run block targeting strategy. For v1, it is good enough. But I figure out some possible way to remove it so that UX will be even better.

**Comment by HananoshikaYomaru** [comment]
in v1.0.2, `id` is no longer needed. 

the starting tag syntax is as easy as `%% run start <expression> %%`

**Comment by stef-rausch** [comment]
Fantastic! This plugin is getting better and better by the day. 👏
