### ISSUE TITLE
Feature Request: Remove notification if there are no run blocks to execute.

### ISSUE THREAD

**Issue by stef-rausch** [HananoshikaYomaru/obsidian-run#4]
A notification is displayed on every save, even if there are no `run blocks` to execute. This can be annoying.

The UX can be enhanced if the notification level can be set -- options:

- No notification at all. Just execute the `run blocks`. The user can use `console.log` to check for any diagnostics.
- Notify the user if there are any errors.
- Always notify the user -- this is the current approach of the plugin.

Keep up the good work!

**Comment by HananoshikaYomaru** [comment]
@StefanoRausch thx, I will definitely look into it. Btw, please leave a star if you like the plugin and want to support.

**Comment by stef-rausch** [comment]
And starred it is. 😉

**Comment by stef-rausch** [comment]
Thank you for enhancing the experience. 👏
