### ISSUE TITLE
Feature Request: Allow variables defined in one "run block" to be used in all subsequent "run blocks" -- page-level scoping

### ISSUE THREAD

**Issue by stef-rausch** [HananoshikaYomaru/obsidian-run#7]
See start of the discussion in https://github.com/HananoshikaYomaru/obsidian-run/issues/6.

I would like to be able to define the following -- simple example:

```
%% start run 01

~~~js
const modal = app.plugins.plugins.modalforms.api
const obs = await self.require.import("[[user.script.obsidian.delay-until-synced.mjs]]")
const timer = 1000
~~~

%%
```

and to re-use the variables in a following `run block`:

```
%% start run 02

~~~js
obs.delayUntilSynced(timer, () => {
    const data = modal.openForm("test-form")
    console.log(data)
}, {omit: ["name"]})

%%
```

The idea is to consolidate all variable declarations in one place for easier management.

Furthermore, if I would have to call the `openForm` modal function in another `run block`, I currently have to re-declare the `access` to the API -- an additional step I would like to avoid.

The icing on the cake would be that any `run block` could use any `page-level (scoped) variables` wherever they are declared.

**Comment by HananoshikaYomaru** [comment]
OK. Interesting. This basically make the whole doc a jupyter notebook. I am not sure about I want to do this because this is not easy. And not what I want this plugin to go.

**Comment by HananoshikaYomaru** [comment]
<img width="826" alt="CleanShot 2023-10-03 at 09 23 39@2x" src="https://github.com/HananoshikaYomaru/obsidian-run/assets/43137033/6e2b861c-7b72-4551-9a5b-70e22d758a2c">

**Comment by stef-rausch** [comment]
Fair enough and thanks for looking into it.
