### ISSUE TITLE
Await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by stef-rausch** [HananoshikaYomaru/obsidian-run#9]
**Describe the bug**

`Async` function calls are not possible in the `run start` block.

**To Reproduce**

I am trying to run the following code:

~~~
%% run start 0

```js
const {reverse} = await self.require.import("[[user.script.fp.reverse.mjs]]")

const a = [1, 2, 3]
const b = reverse(a)

return `a = ${a}\nb = ${b}`
```

%%
~~~

`Run` generates the following end tag metadata:

~~~
%% run end

error: await is only valid in async functions and the top level bodies of modules

%%
~~~

**Expected behavior**

The output should be:

~~~
a = 1,2,3
b = 3,2,1
~~~

The following `Templater` snippet works as expected:

~~~
<%*
const {reverse} = await self.require.import("[[user.script.fp.reverse.mjs]]")

const a = [1, 2, 3]
const b = reverse(a)

tR += `a = ${a}\nb = ${b}`
_%>
~~~

**Additional context**

~~~
SYSTEM INFO:

Obsidian version: v1.4.14
Installer version: v1.4.14
Operating system: Windows 11 Home Single Language 10.0.22621
Login status: logged in
Catalyst license: supporter
Insider build toggle: on
Live preview: on
Legacy editor: off
Base theme: light
Community theme: Minimal v7.2.3
Snippets enabled: 33
Restricted mode: off
Plugins installed: 49
Plugins enabled: 43
~~~

**Comment by HananoshikaYomaru** [comment]
this is indeed a bug.

**Comment by HananoshikaYomaru** [comment]
@StefanoRausch  I think I know how to fix this. But I can see that you are using some advanced techniques. Do you want to have a online call so that I can understand you needs and also I put this in the `Advanced usage` section of the readme?

**Comment by HananoshikaYomaru** [comment]
this is fixed in 1.0.5

**Comment by stef-rausch** [comment]
Sorry, I was out and about.

I updated to version `1.0.5` and `Run` now shows me the following:

![image](https://github.com/HananoshikaYomaru/obsidian-run/assets/1460531/c181b4e8-efbb-4289-bd46-0217ed0a3d95)

It looks like the plugin is not waiting for the promise to resolve.

I am available right now, if you want to chat.

**Comment by HananoshikaYomaru** [comment]
come to my discord -> https://discord.gg/VYNGp7Z5

**Comment by HananoshikaYomaru** [comment]
I am not available right now, but leave me a message in the channel and we will figure out a time.

**Comment by HananoshikaYomaru** [comment]
that is weird, I have no problem resolving the promise. 

![CleanShot 2023-10-04 at 13 55 17](https://github.com/HananoshikaYomaru/obsidian-run/assets/43137033/8043f82a-fafd-4d94-b692-d2b5af9ead2b)

**Comment by stef-rausch** [comment]
Version `1.0.5` does not resolve the issue. Reopened: see https://github.com/HananoshikaYomaru/obsidian-run/issues/14.
